### ISSUE TITLE
2.10 missing features

### ISSUE THREAD

**Issue by szepeviktor** [olsh/Feedly-Notifier-Firefox#111]
After installing 2.10 these are gone:

- right click
- middle click
- counter

But there is a `Show counter` option.

**Comment by olsh** [comment]
> right click
middle click

You can read about it here
https://github.com/olsh/Feedly-Notifier-Firefox/issues/108#issuecomment-74654389

> counter

Are you using palemoon? 
The new version is compatible only with Firefox 36+ because of [the new API](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_toggle#badge)

**Comment by szepeviktor** [comment]
I've tries in Firefox 34 and Waterfox 34 (64 bit)

**Comment by szepeviktor** [comment]
Thank you for your answers.
